name: Generate 3D Contribution Graph
 
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:
  push:
    branches:
      - main
 
permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: dimmy98
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and Push
        run: |
          git add -A .
          git diff --quiet && git diff --staged --quiet || (git commit -m "🎨 Update 3D contribution graph" && git push)
