name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Generate the snake files using a stable version
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dimmy98
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the generated files to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
